# Site settings
title: hand | paper | lake
email: bildzeitung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software from Canada
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bildzeitung.github.io"
twitter_username: mrdanielklein
github_username:  bildzeitung

# Build settings
markdown: kramdown
